declare const shaonq:{
	is: {
		android: boolean,
		ie: boolean,
		ios: boolean,
		wechat: boolean,
	},
	regexp: {},
	cookie: {},
	session: {},
	store: {},
	dom: {},
	date: {
		format: (date:Date,src?:string) => string ,
		toDate: (date:string|number) => Date ,
		today: (src?:string) => string ,
	},
	loadJs: (src: string) => promise <void> ,
	loadCss: (src: string, id ? : string) => void,
	uniqueId: (before:string) => string,
	refreshOffset: (el: HTMLElement ,offset:[string,string]) => void,
	hideToast: (id:string) => void,
	toast: (content:string,time?:number) => string,
	showLoading: (content:string) => string,
	showSuccess: (content:string,time?:number) => string,
	alert: (content:string,extend?:{}) => string,
	showNearby: (options:{})=> string,
	showModal:  (options:string|{})=> string,
	showPopover: (options:{})=> string,
	showDropdown: (options:{})=> string,
	showContextMenu: (options:{})=> string,
	uploadAvatar: (options:{})=> string,
	addMoveEvent:(options:{})=> string,
	showImageView: (node:HTMLElement)=> string,
	stringify: (val:JSON) => string,
	parse: (val:string) => JSON,
	clone: (val:JSON) => JSON,
	toPercent: (a:string)=> string,
	toThousands:(val:string)=> string,
	toMB: (bytes:number)=> string,
	setData: (object:{}, path:string, defaultValue:any)=>{},
	merge: (object:{}, source={})=> {}
};
export default shaonq;
